import type {
  AppUser,
  Hackathon,
  LeaderboardEntry,
  Submission,
  Team,
} from '../types/domain';

export const SEED_USERS: AppUser[] = [
  {
    id: 'user-admin',
    email: 'admin@handoverhq.dev',
    displayName: '김운영',
    primaryRole: 'pm',
    isAdmin: true,
  },
  {
    id: 'user-front',
    email: 'frontend@handoverhq.dev',
    displayName: '김프론트',
    primaryRole: 'frontend',
  },
];

export const SEED_HACKATHONS: Hackathon[] = [
  {
    id: 'hackathon-spring-ai',
    slug: '2026-spring-ai-hackathon',
    title: '2026 Spring AI Hackathon',
    organizer: 'AI Innovation Lab',
    summary: '명세서 기반 MVP를 빠르게 완성하고 제출까지 이어지는 AI 해커톤',
    description:
      'AI와 머신러닝을 활용한 혁신적인 솔루션을 개발하는 해커톤입니다. 초보 참가자도 길을 잃지 않도록 제출 흐름과 팀 구성을 명확하게 안내합니다.',
    status: 'active',
    location: '온라인',
    tags: ['AI/ML', '웹개발', '데이터'],
    submissionDeadline: '2026-03-30T10:00:00+09:00',
    eventEndAt: '2026-04-06T10:00:00+09:00',
    participants: 156,
    teamCount: 42,
    teamMinSize: 2,
    teamMaxSize: 4,
    published: true,
    guideLinks: [
      { label: '대회 안내 문서', url: 'https://example.com/guides/hackathon-guide' },
      { label: '제출 규칙 확인', url: 'https://example.com/guides/submission-guide' },
    ],
    guideItems: [
      '로그인 없이 탐색은 가능하지만 팀 생성과 제출은 인증이 필요합니다.',
      '최종 제출 후에는 수정이 제한되며, 제출 시각과 버전 이력이 저장됩니다.',
      'GitHub 저장소와 배포 링크는 외부에서 접근 가능해야 합니다.',
    ],
    evaluationCriteria: [
      {
        id: 'innovation',
        label: '혁신성',
        weight: 30,
        description: '문제 정의와 해결 방식이 독창적인지 평가합니다.',
      },
      {
        id: 'technical',
        label: '기술력',
        weight: 30,
        description: '구현 난이도와 안정성을 평가합니다.',
      },
      {
        id: 'practical',
        label: '실용성',
        weight: 25,
        description: '실제 서비스로 이어질 가능성을 봅니다.',
      },
      {
        id: 'completion',
        label: '완성도',
        weight: 15,
        description: 'UI/UX와 제출 품질, 시연 가능 여부를 평가합니다.',
      },
    ],
    prizes: [
      { rank: 1, title: '대상', amount: '5,000,000원', description: '총점 1위 팀' },
      { rank: 2, title: '최우수상', amount: '3,000,000원', description: '총점 2위 팀' },
      { rank: 3, title: '우수상', amount: '2,000,000원', description: '총점 3위 팀' },
    ],
    schedule: [
      {
        date: '2026-03-24T10:00:00+09:00',
        title: '참가 등록 및 팀 빌딩',
        description: '참가 등록과 팀 구성을 진행합니다.',
        status: 'completed',
      },
      {
        date: '2026-03-30T10:00:00+09:00',
        title: '1차 기획서 제출',
        description: '기획서 링크 또는 문서를 제출합니다.',
        status: 'upcoming',
      },
      {
        date: '2026-04-06T10:00:00+09:00',
        title: '최종 웹 링크 제출',
        description: '배포 URL과 GitHub 저장소를 제출합니다.',
        status: 'upcoming',
      },
      {
        date: '2026-04-13T10:00:00+09:00',
        title: '솔루션 PDF 제출',
        description: '최종 솔루션 PDF와 시연 링크를 업로드합니다.',
        status: 'upcoming',
      },
    ],
    teamPolicy: [
      '팀장은 제출 권한을 갖고, 팀원은 초안 저장과 수정 제안이 가능합니다.',
      '팀 구성은 2명 이상 4명 이하입니다.',
      '연락 링크는 공개되므로 접근 가능한 URL만 등록합니다.',
    ],
  },
  {
    id: 'hackathon-web3',
    slug: 'web3-innovation-challenge',
    title: 'Web3 Innovation Challenge',
    organizer: '블록체인협회',
    summary: '서비스형 운영 허브 구조를 Web3 해커톤에 적용하는 챌린지',
    description: '참가자와 심사자가 모두 같은 링크로 필요한 정보를 확인할 수 있는 운영 허브를 요구합니다.',
    status: 'active',
    location: '서울 코엑스',
    tags: ['블록체인', '웹개발', '스마트 컨트랙트'],
    submissionDeadline: '2026-04-20T18:00:00+09:00',
    eventEndAt: '2026-05-05T18:00:00+09:00',
    participants: 89,
    teamCount: 28,
    teamMinSize: 2,
    teamMaxSize: 5,
    published: true,
    guideLinks: [{ label: '운영 규칙', url: 'https://example.com/web3/rules' }],
    guideItems: ['배포 링크와 저장소 링크는 필수입니다.', '스마트 컨트랙트 주소는 제출 후 별도 검증합니다.'],
    evaluationCriteria: [
      {
        id: 'utility',
        label: '서비스 가치',
        weight: 35,
        description: '실제 활용 가능성과 사용자 가치',
      },
      {
        id: 'technical',
        label: '구현 완성도',
        weight: 35,
        description: '아키텍처와 구현 품질',
      },
      {
        id: 'presentation',
        label: '설명력',
        weight: 30,
        description: '시연과 제출물의 명확성',
      },
    ],
    prizes: [
      { rank: 1, title: '1위', amount: '3,000,000원', description: '최고 점수 팀' },
      { rank: 2, title: '2위', amount: '1,500,000원', description: '2위 팀' },
    ],
    schedule: [
      {
        date: '2026-03-26T19:00:00+09:00',
        title: '오리엔테이션',
        description: '과제 설명과 팀 소개',
        status: 'completed',
      },
      {
        date: '2026-04-10T18:00:00+09:00',
        title: '중간 점검',
        description: 'MVP 진행 상황 공유',
        status: 'upcoming',
      },
      {
        date: '2026-04-20T18:00:00+09:00',
        title: '최종 제출',
        description: '배포 URL과 저장소 제출',
        status: 'upcoming',
      },
    ],
    teamPolicy: ['최대 5인 팀 구성', '외부 링크는 공개 검증 가능해야 함'],
  },
  {
    id: 'hackathon-sustainable',
    slug: 'sustainable-tech-hackathon',
    title: 'Sustainable Tech Hackathon',
    organizer: '에코재단',
    summary: '친환경 기술과 서비스 운영 경험을 함께 평가하는 해커톤',
    description: '에너지, 모빌리티, 스마트시티 주제를 대상으로 친환경 서비스 아이디어를 구현합니다.',
    status: 'upcoming',
    location: '하이브리드',
    tags: ['친환경', 'IoT', '스마트시티'],
    submissionDeadline: '2026-05-10T10:00:00+09:00',
    eventEndAt: '2026-05-25T18:00:00+09:00',
    participants: 0,
    teamCount: 0,
    teamMinSize: 2,
    teamMaxSize: 4,
    published: true,
    guideLinks: [],
    guideItems: ['세부 규칙은 추후 공개됩니다.'],
    evaluationCriteria: [],
    prizes: [],
    schedule: [],
    teamPolicy: ['상세 정책은 추후 공개'],
  },
  {
    id: 'hackathon-health',
    slug: 'healthtech-innovation-2026',
    title: 'HealthTech Innovation 2026',
    organizer: '서울대병원',
    summary: '헬스케어 데이터와 환자 경험을 중심으로 한 서비스 해커톤',
    description: '헬스케어 데이터, 환자 경험, AI 진단 지원을 주제로 한 서비스형 해커톤입니다.',
    status: 'upcoming',
    location: '온라인',
    tags: ['헬스케어', 'AI', '모바일'],
    submissionDeadline: '2026-05-15T10:00:00+09:00',
    eventEndAt: '2026-06-01T18:00:00+09:00',
    participants: 0,
    teamCount: 0,
    teamMinSize: 2,
    teamMaxSize: 4,
    published: true,
    guideLinks: [],
    guideItems: ['세부 규칙은 추후 공개됩니다.'],
    evaluationCriteria: [],
    prizes: [],
    schedule: [],
    teamPolicy: ['상세 정책은 추후 공개'],
  },
];

export const SEED_TEAMS: Team[] = [
  {
    id: 'team-ai-innovators',
    hackathonId: 'hackathon-spring-ai',
    ownerId: 'user-front',
    name: 'AI Innovators',
    description:
      '추천 시스템 MVP를 완성 중입니다. 백엔드와 디자이너를 보강해서 제출 품질을 끌어올릴 팀원을 찾습니다.',
    currentSize: 3,
    maxSize: 4,
    isRecruiting: true,
    desiredRoles: ['backend', 'designer'],
    techTags: ['React', 'Supabase', 'AI/ML'],
    contactUrl: 'https://discord.gg/example',
    updatedAt: '2026-03-24T20:10:00+09:00',
    members: [
      { profileId: 'user-front', displayName: '김프론트', roleLabel: '팀장 / 프론트엔드', isOwner: true },
      { profileId: 'member-ai-1', displayName: '박모델', roleLabel: 'AI 엔지니어', isOwner: false },
      { profileId: 'member-plan-1', displayName: '정기획', roleLabel: '서비스 기획', isOwner: false },
    ],
  },
  {
    id: 'team-web3-warriors',
    hackathonId: 'hackathon-web3',
    ownerId: 'user-admin',
    name: 'Web3 Warriors',
    description: '지갑 연결과 커뮤니티 리워드 기능을 구현 중입니다. 프론트엔드와 스마트 컨트랙트 경험자를 찾습니다.',
    currentSize: 2,
    maxSize: 4,
    isRecruiting: true,
    desiredRoles: ['frontend', 'smart-contract'],
    techTags: ['Solidity', 'Wallet', 'Next UI'],
    contactUrl: 'https://t.me/example',
    updatedAt: '2026-03-24T15:40:00+09:00',
    members: [
      { profileId: 'user-admin', displayName: '김운영', roleLabel: '팀장 / PM', isOwner: true },
      { profileId: 'member-chain-1', displayName: '최체인', roleLabel: '블록체인 엔지니어', isOwner: false },
    ],
  },
  {
    id: 'team-data-wizards',
    hackathonId: 'hackathon-spring-ai',
    ownerId: 'member-data-1',
    name: 'Data Wizards',
    description: '데이터 분석과 시각화 파이프라인을 안정화한 상태입니다. 모집은 종료되었습니다.',
    currentSize: 4,
    maxSize: 4,
    isRecruiting: false,
    desiredRoles: [],
    techTags: ['Python', 'Data Viz'],
    contactUrl: 'https://discord.gg/example2',
    updatedAt: '2026-03-23T19:20:00+09:00',
    members: [
      { profileId: 'member-data-1', displayName: '장데이터', roleLabel: '팀장 / 데이터', isOwner: true },
      { profileId: 'member-data-2', displayName: '이시각', roleLabel: '데이터 시각화', isOwner: false },
      { profileId: 'member-data-3', displayName: '강백엔드', roleLabel: '백엔드', isOwner: false },
      { profileId: 'member-data-4', displayName: '윤디자인', roleLabel: '디자인', isOwner: false },
    ],
  },
];

export const SEED_SUBMISSIONS: Submission[] = [
  {
    id: 'submission-ai-innovators',
    hackathonId: 'hackathon-spring-ai',
    teamId: 'team-ai-innovators',
    proposalSummary: '해커톤 참가자와 심사자를 위한 제출 가드 중심 운영 허브',
    proposalUrl: 'https://example.com/proposal/ai-innovators',
    deployUrl: 'https://handover-ai-innovators.vercel.app',
    githubUrl: 'https://github.com/example/ai-innovators',
    solutionPdfUrl: '',
    demoVideoUrl: '',
    status: 'draft',
    updatedAt: '2026-03-24T21:10:00+09:00',
    finalSubmittedAt: null,
    versions: [
      {
        versionNumber: 1,
        proposalSummary: '초안 저장 버전',
        proposalUrl: 'https://example.com/proposal/ai-innovators',
        deployUrl: 'https://handover-ai-innovators.vercel.app',
        githubUrl: 'https://github.com/example/ai-innovators',
        solutionPdfUrl: '',
        demoVideoUrl: '',
        savedAt: '2026-03-24T21:10:00+09:00',
      },
    ],
  },
];

export const SEED_LEADERBOARD: LeaderboardEntry[] = [
  {
    id: 'leaderboard-data-wizards',
    hackathonId: 'hackathon-spring-ai',
    teamId: 'team-data-wizards',
    teamName: 'Data Wizards',
    rank: 1,
    totalScore: 92.5,
    participantScore: 46,
    judgeScore: 46.5,
    submittedAt: '2026-03-23T18:40:00+09:00',
    projectUrl: 'https://example.com/projects/data-wizards',
  },
  {
    id: 'leaderboard-ai-innovators',
    hackathonId: 'hackathon-spring-ai',
    teamId: 'team-ai-innovators',
    teamName: 'AI Innovators',
    rank: 2,
    totalScore: 88.2,
    participantScore: 43.5,
    judgeScore: 44.7,
    submittedAt: '2026-03-24T21:10:00+09:00',
    projectUrl: 'https://handover-ai-innovators.vercel.app',
  },
  {
    id: 'leaderboard-web3-warriors',
    hackathonId: 'hackathon-web3',
    teamId: 'team-web3-warriors',
    teamName: 'Web3 Warriors',
    rank: 1,
    totalScore: 90.1,
    participantScore: 44,
    judgeScore: 46.1,
    submittedAt: '2026-03-24T13:20:00+09:00',
    projectUrl: 'https://example.com/projects/web3-warriors',
  },
];
